apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devsecops-api-ingress
  namespace: staging
  annotations:
    # cert-manager issues a TLS certificate automatically
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.staging.example.com       # replace with your domain
      secretName: devsecops-api-tls
  rules:
    - host: api.staging.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devsecops-api
                port:
                  name: http
